CREATE TABLE USUARIOS (
id BIGINT IDENTITY(1,1) PRIMARY KEY,
nombres VARCHAR(200) NULL,
apellidos VARCHAR(200) NULL,
direccion VARCHAR(200) NULL,
fecha_nacimiento DATE NULL,
contrasenia VARCHAR(300) NULL,
correo_electronico VARCHAR(200) NULL,
estado TINYINT DEFAULT 0,
)


CREATE TABLE LOGS (
id BIGINT IDENTITY(1,1) PRIMARY KEY,
usuario_id BIGINT,
fecha DATETIME NULL,
CONSTRAINT FK_LOGS_USUARIO_ID FOREIGN KEY (usuario_id) REFERENCES USUARIOS(id)
)


