CREATE TABLE USUARIOS (
id BIGINT IDENTITY(1,1) PRIMARY KEY,
nombres VARCHAR(200) NULL,
apellidos VARCHAR(200) NULL,
direccion VARCHAR(200) NULL,
fecha_nacimiento DATE NULL,
contrasenia VARCHAR(300) NULL,
correo_electronico VARCHAR(200) NULL,
)


CREATE TABLE CORREOS (
id BIGINT IDENTITY(1,1) PRIMARY KEY,
usuario_id BIGINT,
estado TINYINT DEFAULT 0,
tipo VARCHAR(5),
CONSTRAINT FK_CORREOS_USUARIO_ID FOREIGN KEY (usuario_id) REFERENCES USUARIOS(id)
)